# Generated by Django 2.2.4 on 2020-05-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200512_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
