# Generated by Django 2.2.4 on 2020-05-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default='0001-01-01'),
            preserve_default=False,
        ),
    ]
